use_frameworks!

platform :ios, '9.0'

target 'BeeKit_Example' do
  pod 'BeeKit-Swift', :path => '../'
  pod 'SnapKit'
  
  pod 'CatalogByConvention'

  target 'BeeKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
